## Ejemplo de clase para Autograd 

In [1]:
import torch
from torch.autograd import grad

$$f(x,y,z) = (x+y)z $$

para $x = -2$, $y = 5$, $z = -4$ 

In [2]:
x = torch.tensor([-2.], requires_grad=True)
y = torch.tensor([5.], requires_grad=True)
z = torch.tensor([-4.], requires_grad=True)
f = (x+y)*z #paso forward

In [3]:
f

tensor([-12.], grad_fn=<MulBackward0>)

Por defecto, PyTorch construirá automáticamente el grafo computacional si hay variables con el parámetro `requires_grad=True`.

Derivada de $f$ con respecto a $x$

In [4]:
grad(f, x, retain_graph=True)

(tensor([-4.]),)

El parámetro `retain_graph=True` hace que el grafo se mantenga en memoria, ya que luego de calcular gradientes, por defecto se libera

Derivada de $f$ con respecto a $y$

In [5]:
grad(f, y, retain_graph=True)

(tensor([-4.]),)

In [6]:
grad(f,z)

(tensor([3.]),)

In [7]:
grad(f,z)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

<br>
<br>