Thanks to: Sebastian Raschka (sraschka@wisc.edu)  

---

In [1]:
from scipy.signal import correlate2d, convolve2d
import torch

In [2]:
a = torch.tensor([[1.1, 1.2, 1.3],
                  [2.1, 2.2, 2.3],
                  [3.1, 3.2, 3.3]])

In [3]:
print(a.shape)

torch.Size([3, 3])


In [4]:
conv_pytorch = torch.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3, 3))
with torch.no_grad():
    conv_pytorch.bias.zero_()
    
conv_pytorch.weight

Parameter containing:
tensor([[[[ 0.2810,  0.2938,  0.0777],
          [-0.0454,  0.2108,  0.3242],
          [-0.1402, -0.2465,  0.1306]]]], requires_grad=True)

In [5]:
conv_weight_numpy = conv_pytorch.weight.detach().numpy().reshape(3, 3)
conv_weight_numpy

array([[ 0.28095603,  0.29378068,  0.0777487 ],
       [-0.04544958,  0.21081042,  0.3241987 ],
       [-0.14024961, -0.24645063,  0.13055484]], dtype=float32)

## Cross-correlation

In [6]:
conv_pytorch(a.view(1, 1, 3, 3))

tensor([[[[1.0841]]]], grad_fn=<ConvolutionBackward0>)

In [7]:
correlate2d(a.numpy(), conv_weight_numpy, mode='valid')

array([[1.0840727]], dtype=float32)

# Real convolution

In [8]:
convolve2d(a.numpy(), conv_weight_numpy, mode='valid')

array([[2.8138852]], dtype=float32)

In [9]:
a_mod = torch.tensor([[3.3, 3.2, 3.1],
                      [2.3, 2.2, 2.1],
                      [1.3, 1.2, 1.1]])


conv_pytorch(a_mod.view(1, 1, 3, 3))

tensor([[[[2.8139]]]], grad_fn=<ConvolutionBackward0>)