Thanks to: Sebastian Raschka (sraschka@wisc.edu)  

---

In [1]:
from scipy.signal import correlate2d, convolve2d
import torch

In [2]:
a = torch.tensor([[1.1, 1.2, 1.3],
                  [2.1, 2.2, 2.3],
                  [3.1, 3.2, 3.3]])

In [3]:
print(a.shape)

torch.Size([3, 3])


In [4]:
conv_pytorch = torch.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3, 3))
with torch.no_grad():
    conv_pytorch.bias.zero_()
    
conv_pytorch.weight

Parameter containing:
tensor([[[[ 0.1333,  0.3063,  0.0707],
          [-0.0289,  0.1689, -0.3029],
          [-0.3290,  0.0066, -0.3108]]]], requires_grad=True)

In [5]:
conv_weight_numpy = conv_pytorch.weight.detach().numpy().reshape(3, 3)
conv_weight_numpy

array([[ 0.13331592,  0.30631295,  0.07068673],
       [-0.02890083,  0.16890314, -0.3029177 ],
       [-0.32898784,  0.00657824, -0.31079137]], dtype=float32)

## Cross-correlation

In [6]:
conv_pytorch(a.view(1, 1, 3, 3))

tensor([[[[-1.8041]]]], grad_fn=<ConvolutionBackward0>)

In [7]:
correlate2d(a.numpy(), conv_weight_numpy, mode='valid')

array([[-1.8041232]], dtype=float32)

# Real convolution

In [8]:
convolve2d(a.numpy(), conv_weight_numpy, mode='valid')

array([[0.54659986]], dtype=float32)

In [9]:
a_mod = torch.tensor([[3.3, 3.2, 3.1],
                      [2.3, 2.2, 2.1],
                      [1.3, 1.2, 1.1]])


conv_pytorch(a_mod.view(1, 1, 3, 3))

tensor([[[[0.5466]]]], grad_fn=<ConvolutionBackward0>)