Thanks to: Sebastian Raschka (sraschka@wisc.edu)  

---

<a href="https://colab.research.google.com/github/andrescastro-itm/IA_ITM_2025-2/blob/main/Clase23/2-cross-correlation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from scipy.signal import correlate2d, convolve2d
import torch

In [2]:
a = torch.tensor([[1.1, 1.2, 1.3],
                  [2.1, 2.2, 2.3],
                  [3.1, 3.2, 3.3]])

In [3]:
print(a.shape)

torch.Size([3, 3])


In [4]:
conv_pytorch = torch.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3, 3))
with torch.no_grad():
    conv_pytorch.bias.zero_()
    
conv_pytorch.weight

Parameter containing:
tensor([[[[-0.2551, -0.0743, -0.2289],
          [-0.0353,  0.1103, -0.0142],
          [ 0.3100,  0.0075,  0.1252]]]], requires_grad=True)

In [5]:
conv_weight_numpy = conv_pytorch.weight.detach().numpy().reshape(3, 3)
conv_weight_numpy

array([[-0.25511682, -0.07431602, -0.22891057],
       [-0.03525069,  0.11030272, -0.01422635],
       [ 0.30999395,  0.00745472,  0.12518182]], dtype=float32)

## Cross-correlation

In [6]:
conv_pytorch(a.view(1, 1, 3, 3))

tensor([[[[0.8665]]]], grad_fn=<ConvolutionBackward0>)

In [7]:
correlate2d(a.numpy(), conv_weight_numpy, mode='valid')

array([[0.8664639]], dtype=float32)

# Real convolution

In [8]:
convolve2d(a.numpy(), conv_weight_numpy, mode='valid')

array([[-1.1079676]], dtype=float32)

In [9]:
a_mod = torch.tensor([[3.3, 3.2, 3.1],
                      [2.3, 2.2, 2.1],
                      [1.3, 1.2, 1.1]])


conv_pytorch(a_mod.view(1, 1, 3, 3))

tensor([[[[-1.1080]]]], grad_fn=<ConvolutionBackward0>)